version: "3.1"

services:
  api-server:
    container_name: mo-berries
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.docker
    build: .
    volumes:
      - ./:/var/www/source_code
    depends_on:
      - db
    ports:
      - "80:8000"
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - mo-berries-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: atiqul@mo-berries.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - db
    ports:
      - 8080:80
volumes:
  mo-berries-db:
