# Generated by Django 3.0.7 on 2020-11-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0003_auto_20201101_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('in_progress', 'IN_PROGRESS'), ('delivered', 'DELIVERED'), ('canceled', 'CANCELED')], default='pending', max_length=15, verbose_name='Order Status'),
        ),
    ]
