# Generated by Django 3.0.7 on 2020-11-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0004_auto_20201102_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='flavor',
            field=models.CharField(choices=[('margarita', 'MARGARITA'), ('marinara', 'MARINARA'), ('salami', 'SALAMI')], default='salami', max_length=15, verbose_name='Pizza Flavors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE')], default='small', max_length=15, verbose_name='Pizza Sizes'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order', 'flavor', 'size')},
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='pizza',
        ),
    ]
