# Generated by Django 3.0.7 on 2020-11-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0005_auto_20201102_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
